id: P001857
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:26:22.446166
source_metadata:
  id: bdr:W2DB13640
  title: སུམ་པའི་སྨན་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    18c5221103064f0da2dac20cbc0ce0b6:
      image_group_id: I1PD30943
      title: ''
      volume_number: 1
      total_pages: 550
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
