id: P001857
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB13640
  title: སུམ་པའི་སྨན་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    18c5221103064f0da2dac20cbc0ce0b6:
      image_group_id: I1PD30943
      title: ''
      volume_number: 1
      total_pages: 550
      base_file: v001.txt
